# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name rw_Metropolis
#' @title A Metropolis sampler using Rcpp
#' @description A Metropolis sampler using Rcpp
#' @param N the number of samples
#' @param x0 the number of between-sample random number
#' @param sigma variance
#' @return a List with a random sample of size \code{n}
#' @export
dLaplace <- function(x) {
    .Call('_StatComp20062_dLaplace', PACKAGE = 'StatComp20062', x)
}

rw_Metropolis <- function(sigma, x0, N) {
    .Call('_StatComp20062_rw_Metropolis', PACKAGE = 'StatComp20062', sigma, x0, N)
}

